INSERT INTO URL (ID,BASEURL,SHORTURL) VALUES (1,'http://www.google.com','A75EGAT89H')
INSERT INTO URL (ID,BASEURL,SHORTURL) VALUES (2,'http://www.notarius.com/en/','HAPPYPATH1')
INSERT INTO URL (ID,BASEURL,SHORTURL) VALUES (3,'http://www.notarius.com/fr/','UNHAPPYPA1')
INSERT INTO URL (ID,BASEURL,SHORTURL) VALUES (4,'http://www.notarius.com/fr/','UNHAPPYPA2')